### Make BioSample table

In [17]:
metadata

Empty DataFrame
Columns: [T, Date, Bath, Tank, SourceSite, Extract, Temp, Nutrients, Fraction, BathName, TP, TP_Bath, TP_Bath_Site, Bath_Site, Partition, Treatment, SiteNumeric]
Index: []

In [41]:
from qiime2 import Artifact

table = Artifact.load('DIVERSITY_epiphytes/rarefied_table.qza').view(pd.DataFrame)

In [42]:
import pandas as pd
import glob

!mkdir biosample_sra

biosample = pd.DataFrame(columns=[
    'replicate','description','*geo_loc_name','*host',
    '*collection_date','sample_title','*organism','*env_medium',
    '*lat_lon','*env_broad_scale','*env_local_scale','source_site','treatment','time point','original_id'])

biosample.index.name = '*sample_name'


organism = 'epiphytic metagenome'
host = 'Halophila stipulacea'
environmental_medium = 'water'
broad_scale_environmental_context = 'marine seagrass meadow'

metadata = pd.read_csv('metadata/metadata.tsv',sep='\t',index_col=0)
metadata = metadata.loc[metadata.Fraction!='water']

samples = [i.split('/')[-1].split('_')[0] for i in glob.glob('raw_reads/*.fastq.gz')]

samples = set(samples)

replicate = 'biological replicate %i'

replicate_counter = {}

description = 'Epiphytic metagenome sample from Halophila stipulacea in a mesocosm experiment. Source site %s, treatment %s'

collection_dates = ['15-Aug-2019',0,0,'08-Sep-2019',0,'22-Sep-2019',0,0,'13-Oct-2019']

for smpl in samples:
    if smpl not in metadata.index.tolist():
        continue
        
    if smpl not in table.index.tolist():
        continue
        
    geo_loc_name = 'Israel:Hatzeva,DeadSeaAndAravaScienceCenter'
    lat_lon = '30.77 N 35.24 E'
    local_scale_environmental_context = "mesocosm experiment"
    try:
        collection_date = collection_dates[int(metadata.at[smpl,'TP'])]
    except:
        collection_date = '15-Dec-2019'
    timepoint = metadata.at[smpl,'TP']
    source_site = metadata.at[smpl,'SourceSite']
    treatment = metadata.at[smpl,'Treatment']
    try:
        description = 'Epiphytic metagenome sample from Halophila stipulacea in a mesocosm experiment. Source site %s, treatment %s, T%i' % (source_site,treatment,timepoint)
    except:
        timepoint = 0
    if metadata.at[smpl,'Fraction'] == 'Field' and metadata.at[smpl,'SourceSite'] == 'TY' :
        geo_loc_name = 'Israel:Eilat,TurYamBeach'
        lat_lon = '29.51 N 34.92 E'
        local_scale_environmental_context = "Gulf of Aqaba Halophila stipulacea meadow"
        description = 'Epiphytic metagenome sample of Halophila stipulacea from Tur Yam Beach, Eilat'
    elif metadata.at[smpl,'Fraction'] == 'Field' and metadata.at[smpl,'SourceSite'] == 'SB' :
        geo_loc_name = 'Israel:Eilat,SouthBeach'
        lat_lon = '29.49 N 34.91 E'
        local_scale_environmental_context = "Gulf of Aqaba Halophila stipulacea meadow"
        description = 'Epiphytic metagenome sample of Halophila stipulacea from South Beach, Eilat'
    
    if description in replicate_counter:
        replicate_counter[description] += 1
    else:
        replicate_counter[description] = 1
        
    rep = replicate%replicate_counter[description]
    
    
    
    
    biosample.loc[smpl] = [
                    rep,
                    description +', '+ rep,
                    geo_loc_name,
                    host,
                    collection_date,
                    description +', '+ rep,
                    organism,
                    environmental_medium,
                    lat_lon,
                    broad_scale_environmental_context,
                    local_scale_environmental_context,
                    source_site,
                    treatment,
                    timepoint,smpl]
            
for smpl in samples:
    if smpl not in biosample.index:
        print(smpl)
        
biosample.to_csv('biosample_sra/BioSample_metadata_epiphytes.tsv',sep='\t')
biosample

mkdir: cannot create directory ‘biosample_sra’: File exists
AS2214
AS2202
AS2084
Tank-3B
AS2004
Tank-7C
Tank-8C
AS2055
Tank-8B
Tank-2B
Tank-8A
Tank-17A
Tank-17B
Tank-7D
AS2201
Tank-3D
AS2200
Tank-2A
NTC-22
Tank-7A
AS2213
AS2217
Tank-16D
Tank-17C
AS2203
Tank-13D
Tank-12B
Tank-13B
Tank-16B
Tank-2D
Tank-12C
NTC-PCR21
Tank-16C
NTC-PCR22
AS2215
Tank-7B
NTC-21
Tank-13C
Tank-12A
Tank-16A
AS2212
Tank-12D
Tank-2C
Tank-17D
Tank-3C
Tank-13A
Tank-3A
Tank-8D
AS2205

,replicate,description,*geo_loc_name,*host,*collection_date,sample_title,*organism,*env_medium,*lat_lon,*env_broad_scale,*env_local_scale,source_site,treatment,time point,original_id
*sample_name,,,,,,,,,,,,,,,
AS2003,biological replicate 1,Epiphytic metagenome sample from Halophila sti...,"Israel:Hatzeva,DeadSeaAndAravaScienceCenter",Halophila stipulacea,15-Aug-2019,Epiphytic metagenome sample from Halophila sti...,epiphytic metagenome,water,30.77 N 35.24 E,marine seagrass meadow,mesocosm experiment,SB,CTCN,0.0,AS2003
AS2067,biological replicate 1,Epiphytic metagenome sample from Halophila sti...,"Israel:Hatzeva,DeadSeaAndAravaScienceCenter",Halophila stipulacea,08-Sep-2019,Epiphytic metagenome sample from Halophila sti...,epiphytic metagenome,water,30.77 N 35.24 E,marine seagrass meadow,mesocosm experiment,SB,TCN,3.0,AS2067
AS2103,biological replicate 1,Epiphytic metagenome sample from Halophila sti...,"Israel:Hatzeva,DeadSeaAndAravaScienceCenter",Halophila stipulacea,22-Sep-2019,Epiphytic metagenome sample from Halophila sti...,epiphytic metagenome,water,30.77 N 35.24 E,marine seagrass meadow,mesocosm experiment,SB,TCN,5.0,AS2103
AS2011,biological replicate 1,Epiphytic metagenome sample from Halophila sti...,"Israel:Hatzeva,DeadSeaAndAravaScienceCenter",Halophila stipulacea,15-Aug-2019,Epiphytic metagenome sample from Halophila sti...,epiphytic metagenome,water,30.77 N 35.24 E,marine seagrass meadow,mesocosm experiment,SB,CTN,0.0,AS2011
AS2076,biological replicate 1,Epiphytic metagenome sample from Halophila sti...,"Israel:Hatzeva,DeadSeaAndAravaScienceCenter",Halophila stipulacea,08-Sep-2019,Epiphytic metagenome sample from Halophila sti...,epiphytic metagenome,water,30.77 N 35.24 E,marine seagrass meadow,mesocosm experiment,TY,TN,3.0,AS2076
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
AS2058,biological replicate 4,Epiphytic metagenome sample from Halophila sti...,"Israel:Hatzeva,DeadSeaAndAravaScienceCenter",Halophila stipulacea,08-Sep-2019,Epiphytic metagenome sample from Halophila sti...,epiphytic metagenome,water,30.77 N 35.24 E,marine seagrass meadow,mesocosm experiment,SB,CTN,3.0,AS2058
AS2159,biological replicate 4,Epiphytic metagenome sample from Halophila sti...,"Israel:Hatzeva,DeadSeaAndAravaScienceCenter",Halophila stipulacea,13-Oct-2019,Epiphytic metagenome sample from Halophila sti...,epiphytic metagenome,water,30.77 N 35.24 E,marine seagrass meadow,mesocosm experiment,SB,TN,8.0,AS2159
AS2017,biological replicate 5,Epiphytic metagenome sample from Halophila sti...,"Israel:Hatzeva,DeadSeaAndAravaScienceCenter",Halophila stipulacea,15-Aug-2019,Epiphytic metagenome sample from Halophila sti...,epiphytic metagenome,water,30.77 N 35.24 E,marine seagrass meadow,mesocosm experiment,TY,CTN,0.0,AS2017
AS2052,biological replicate 5,Epiphytic metagenome sample from Halophila sti...,"Israel:Hatzeva,DeadSeaAndAravaScienceCenter",Halophila stipulacea,08-Sep-2019,Epiphytic metagenome sample from Halophila sti...,epiphytic metagenome,water,30.77 N 35.24 E,marine seagrass meadow,mesocosm experiment,TY,CTN,3.0,AS2052
AS2075,biological replicate 4,Epiphytic metagenome sample from Halophila sti...,"Israel:Hatzeva,DeadSeaAndAravaScienceCenter",Halophila stipulacea,08-Sep-2019,Epiphytic metagenome sample from Halophila sti...,epiphytic metagenome,water,30.77 N 35.24 E,marine seagrass meadow,mesocosm experiment,SB,TN,3.0,AS2075

In [52]:
import pandas as pd
import glob

!mkdir biosample_sra

biosample = pd.DataFrame(columns=[
    'replicate','description','*geo_loc_name',
    '*collection_date','sample_title','*organism','*env_medium',
    '*lat_lon','*env_broad_scale','*env_local_scale','treatment','timepoint','original_id','depth'])

biosample.index.name = '*sample_name'


organism = 'water metagenome'
environmental_medium = 'artificial seawater'
broad_scale_environmental_context = 'marine seagrass meadow'

metadata = pd.read_csv('metadata/metadata.tsv',sep='\t',index_col=0)
metadata = metadata.loc[metadata.Fraction=='water']

samples = [i.split('/')[-1].split('_')[0] for i in glob.glob('raw_reads/*.fastq.gz')]

samples = set(samples)

replicate = 'biological replicate %i'

replicate_counter = {}

description = 'Water metagenome from a Halophila stipulacea mesocosm. Treatment %s, time point %s'

collection_dates = ['15-Aug-2019',0,0,'08-Sep-2019',0,'22-Sep-2019',0,0,'13-Oct-2019']

for smpl in samples:
    if smpl not in metadata.index.tolist():
        continue
        
    geo_loc_name = 'Israel:Hatzeva,DeadSeaAndAravaScienceCenter'
    lat_lon = '30.77 N 35.24 E'
    local_scale_environmental_context = "mesocosm experiment"
    collection_date = collection_dates[int(metadata.at[smpl,'TP'])]
    timepoint = metadata.at[smpl,'TP']
    treatment = metadata.at[smpl,'Treatment']
    desc = description % (treatment,timepoint)
    
    
    if desc in replicate_counter:
        replicate_counter[desc] += 1
    else:
        replicate_counter[desc] = 1
        
    rep = replicate%replicate_counter[desc]
    
    
    
    
    biosample.loc[smpl] = [
                    rep,
                    desc +', '+ rep,
                    geo_loc_name,
                    collection_date,
                    desc +', '+ rep,
                    organism,
                    environmental_medium,
                    lat_lon,
                    broad_scale_environmental_context,
                    local_scale_environmental_context,
                    treatment,
                    timepoint,smpl,'9m']
            
for smpl in samples:
    if smpl not in biosample.index:
        print(smpl)
        
biosample.to_csv('biosample_sra/BioSample_metadata_water.tsv',sep='\t')
biosample

mkdir: cannot create directory ‘biosample_sra’: File exists
AS2003
AS2067
AS2103
AS2011
AS2076
AS2120
AS2114
AS2214
AS2053
AS2202
AS2033
AS2084
AS2004
AS2140
AS2082
AS2110
AS2086
AS2080
AS2128
AS2057
AS2029
AS2127
AS2050
AS2055
AS2010
AS2116
Tank-8B
AS2136
AS2016
AS2083
AS2087
AS2045
Tank-17A
AS2139
AS2130
AS2024
AS2025
AS2135
AS2143
Tank-7D
AS2126
AS2093
AS2201
AS2064
AS2119
AS2092
AS2081
AS2200
AS2124
AS2146
AS2035
AS2100
AS2158
NTC-22
AS2157
AS2013
AS2023
AS2098
Tank-7A
AS2014
AS2213
AS2070
AS2006
AS2137
AS2089
AS2027
AS2054
AS2138
AS2217
AS2026
AS2036
AS2069
AS2156
AS2131
AS2079
Tank-17C
AS2145
AS2154
AS2203
AS2121
AS2088
AS2041
AS2015
AS2048
AS2002
AS2155
AS2095
AS2034
AS2144
AS2104
AS2028
AS2125
AS2038
AS2068
AS2019
AS2018
AS2051
AS2160
AS2060
Tank-13B
AS2059
AS2042
AS2109
AS2046
AS2030
AS2008
AS2107
AS2077
Tank-16B
AS2065
AS2091
AS2115
AS2007
AS2085
AS2012
AS2132
AS2129
AS2113
AS2123
Tank-12C
AS2096
NTC-PCR21
AS2117
AS2108
AS2106
AS2118
AS2049
AS2073
NTC-PCR22
AS2134
AS2043
AS2149
AS2005
AS2039
AS2063
AS2215
AS2040
AS2044
AS2074
AS2097
NTC-21
Tank-13C
Tank-12A
AS2056
AS2066
AS2212
AS2094
Tank-12D
AS2047
AS2001
AS2078
AS2099
AS2122
AS2009
AS2150
AS2020
AS2153
AS2105
AS2133
AS2147
AS2037
AS2205
AS2148
AS2058
AS2159
AS2017
AS2052
AS2075

,replicate,description,*geo_loc_name,*collection_date,sample_title,*organism,*env_medium,*lat_lon,*env_broad_scale,*env_local_scale,treatment,timepoint,original_id,depth
*sample_name,,,,,,,,,,,,,,
Tank-3B,biological replicate 1,Water metagenome from a Halophila stipulacea m...,"Israel:Hatzeva,DeadSeaAndAravaScienceCenter",08-Sep-2019,Water metagenome from a Halophila stipulacea m...,water metagenome,artificial seawater,30.77 N 35.24 E,marine seagrass meadow,mesocosm experiment,CTCN,3.0,Tank-3B,9m
Tank-7C,biological replicate 1,Water metagenome from a Halophila stipulacea m...,"Israel:Hatzeva,DeadSeaAndAravaScienceCenter",22-Sep-2019,Water metagenome from a Halophila stipulacea m...,water metagenome,artificial seawater,30.77 N 35.24 E,marine seagrass meadow,mesocosm experiment,CTN,5.0,Tank-7C,9m
Tank-8C,biological replicate 2,Water metagenome from a Halophila stipulacea m...,"Israel:Hatzeva,DeadSeaAndAravaScienceCenter",22-Sep-2019,Water metagenome from a Halophila stipulacea m...,water metagenome,artificial seawater,30.77 N 35.24 E,marine seagrass meadow,mesocosm experiment,CTN,5.0,Tank-8C,9m
Tank-2B,biological replicate 2,Water metagenome from a Halophila stipulacea m...,"Israel:Hatzeva,DeadSeaAndAravaScienceCenter",08-Sep-2019,Water metagenome from a Halophila stipulacea m...,water metagenome,artificial seawater,30.77 N 35.24 E,marine seagrass meadow,mesocosm experiment,CTCN,3.0,Tank-2B,9m
Tank-8A,biological replicate 1,Water metagenome from a Halophila stipulacea m...,"Israel:Hatzeva,DeadSeaAndAravaScienceCenter",15-Aug-2019,Water metagenome from a Halophila stipulacea m...,water metagenome,artificial seawater,30.77 N 35.24 E,marine seagrass meadow,mesocosm experiment,CTN,0.0,Tank-8A,9m
Tank-17B,biological replicate 1,Water metagenome from a Halophila stipulacea m...,"Israel:Hatzeva,DeadSeaAndAravaScienceCenter",08-Sep-2019,Water metagenome from a Halophila stipulacea m...,water metagenome,artificial seawater,30.77 N 35.24 E,marine seagrass meadow,mesocosm experiment,TN,3.0,Tank-17B,9m
Tank-3D,biological replicate 1,Water metagenome from a Halophila stipulacea m...,"Israel:Hatzeva,DeadSeaAndAravaScienceCenter",13-Oct-2019,Water metagenome from a Halophila stipulacea m...,water metagenome,artificial seawater,30.77 N 35.24 E,marine seagrass meadow,mesocosm experiment,CTCN,8.0,Tank-3D,9m
Tank-2A,biological replicate 1,Water metagenome from a Halophila stipulacea m...,"Israel:Hatzeva,DeadSeaAndAravaScienceCenter",15-Aug-2019,Water metagenome from a Halophila stipulacea m...,water metagenome,artificial seawater,30.77 N 35.24 E,marine seagrass meadow,mesocosm experiment,CTCN,0.0,Tank-2A,9m
Tank-16D,biological replicate 1,Water metagenome from a Halophila stipulacea m...,"Israel:Hatzeva,DeadSeaAndAravaScienceCenter",13-Oct-2019,Water metagenome from a Halophila stipulacea m...,water metagenome,artificial seawater,30.77 N 35.24 E,marine seagrass meadow,mesocosm experiment,TN,8.0,Tank-16D,9m
Tank-13D,biological replicate 1,Water metagenome from a Halophila stipulacea m...,"Israel:Hatzeva,DeadSeaAndAravaScienceCenter",13-Oct-2019,Water metagenome from a Halophila stipulacea m...,water metagenome,artificial seawater,30.77 N 35.24 E,marine seagrass meadow,mesocosm experiment,TCN,8.0,Tank-13D,9m
Tank-12B,biological replicate 1,Water metagenome from a Halophila stipulacea m...,"Israel:Hatzeva,DeadSeaAndAravaScienceCenter",08-Sep-2019,Water metagenome from a Halophila stipulacea m...,water metagenome,artificial seawater,30.77 N 35.24 E,marine seagrass meadow,mesocosm experiment,TCN,3.0,Tank-12B,9m
Tank-2D,biological replicate 2,Water metagenome from a Halophila stipulacea m...,"Israel:Hatzeva,DeadSeaAndAravaScienceCenter",13-Oct-2019,Water metagenome from a Halophila stipulacea m...,water metagenome,artificial seawater,30.77 N 35.24 E,marine seagrass meadow,mesocosm experiment,CTCN,8.0,Tank-2D,9m
Tank-16C,biological replicate 1,Water metagenome from a Halophila stipulacea m...,"Israel:Hatzeva,DeadSeaAndAravaScienceCenter",22-Sep-2019,Water metagenome from a Halophila stipulacea m...,water metagenome,artificial seawater,30.77 N 35.24 E,marine seagrass meadow,mesocosm experiment,TN,5.0,Tank-16C,9m
Tank-7B,biological replicate 1,Water metagenome from a Halophila stipulacea m...,"Israel:Hatzeva,DeadSeaAndAravaScienceCenter",08-Sep-2019,Water metagenome from a Halophila stipulacea m...,water metagenome,artificial seawater,30.77 N 35.24 E,marine seagrass meadow,mesocosm experiment,CTN,3.0,Tank-7B,9m
Tank-16A,biological replicate 1,Water metagenome from a Halophila stipulacea m...,"Israel:Hatzeva,DeadSeaAndAravaScienceCenter",15-Aug-2019,Water metagenome from a Halophila stipulacea m...,water metagenome,artificial seawater,30.77 N 35.24 E,marine seagrass meadow,mesocosm experiment,TN,0.0,Tank-16A,9m
Tank-2C,biological replicate 1,Water metagenome from a Halophila stipulacea m...,"Israel:Hatzeva,DeadSeaAndAravaScienceCenter",22-Sep-2019,Water metagenome from a Halophila stipulacea m...,water metagenome,artificial seawater,30.77 N 35.24 E,marine seagrass meadow,mesocosm experiment,CTCN,5.0,Tank-2C,9m
Tank-17D,biological replicate 2,Water metagenome from a Halophila stipulacea m...,"Israel:Hatzeva,DeadSeaAndAravaScienceCenter",13-Oct-2019,Water metagenome from a Halophila stipulacea m...,water metagenome,artificial seawater,30.77 N 35.24 E,marine seagrass meadow,mesocosm experiment,TN,8.0,Tank-17D,9m
Tank-3C,biological replicate 2,Water metagenome from a Halophila stipulacea m...,"Israel:Hatzeva,DeadSeaAndAravaScienceCenter",22-Sep-2019,Water metagenome from a Halophila stipulacea m...,water metagenome,artificial seawater,30.77 N 35.24 E,marine seagrass meadow,mesocosm experiment,CTCN,5.0,Tank-3C,9m
Tank-13A,biological replicate 1,Water metagenome from a Halophila stipulacea m...,"Israel:Hatzeva,DeadSeaAndAravaScienceCenter",15-Aug-2019,Water metagenome from a Halophila stipulacea m...,water metagenome,artificial seawater,30.77 N 35.24 E,marine seagrass meadow,mesocosm experiment,TCN,0.0,Tank-13A,9m
Tank-3A,biological replicate 2,Water metagenome from a Halophila stipulacea m...,"Israel:Hatzeva,DeadSeaAndAravaScienceCenter",15-Aug-2019,Water metagenome from a Halophila stipulacea m...,water metagenome,artificial seawater,30.77 N 35.24 E,marine seagrass meadow,mesocosm experiment,CTCN,0.0,Tank-3A,9m
Tank-8D,biological replicate 1,Water metagenome from a Halophila stipulacea m...,"Israel:Hatzeva,DeadSeaAndAravaScienceCenter",13-Oct-2019,Water metagenome from a Halophila stipulacea m...,water metagenome,artificial seawater,30.77 N 35.24 E,marine seagrass meadow,mesocosm experiment,CTN,8.0,Tank-8D,9m

In [53]:
biosamples = pd.read_csv('biosample_sra/BioSample_metadata_epiphytes.tsv',sep='\t',index_col=0)

In [44]:
import glob

sra = pd.DataFrame(columns = [
    'library_ID','title','library_strategy',
    'library_source','library_selection','library_layout',
    'platform','instrument_model','design_description',
    'filetype','filename','filename2']
)

sra.index.name = 'sample_name'

for smpl in biosamples.index:
    biosample = smpl #sample_to_biosample[smpl]
    library_ID = '%s' % smpl
    title = biosamples.loc[biosamples.original_id==smpl]['description'].tolist()[0].replace('metagenome sample','16S-rRNA metabaecoding sequences')+' original ID %s' % biosample
    library_strategy = 'AMPLICON'
    library_source = 'GENOMIC'
    library_selection = 'PCR'
    library_layout = 'paired'
    platform = 'ILLUMINA'
    instrument_model = 'Illumina iSeq 100'
    design_description = 'Single barcode, two-step PCR, V4 fragment'
    filetype = 'fastq'
    R1 = list(glob.glob('raw_reads/%s_*_*_R1_*.fastq.gz'%smpl))[0].split('/')[-1]
    R2 = list(glob.glob('raw_reads/%s_*_*_R2_*.fastq.gz'%smpl))[0].split('/')[-1]
    sra.loc[library_ID] = [biosample,title,library_strategy,library_source,
                           library_selection,library_layout,platform,
                           instrument_model,design_description,filetype,R1,R2]

    
    
sra.to_csv('biosample_sra/sra_metadata_epiphytes.tsv',sep='\t')

In [54]:
biosamples = pd.read_csv('biosample_sra/BioSample_metadata_water.tsv',sep='\t',index_col=0)

In [55]:
import glob

sra = pd.DataFrame(columns = [
    'library_ID','title','library_strategy',
    'library_source','library_selection','library_layout',
    'platform','instrument_model','design_description',
    'filetype','filename','filename2']
)

sra.index.name = 'sample_name'

for smpl in biosamples.index:
    biosample = smpl #sample_to_biosample[smpl]
    library_ID = '%s' % smpl
    title = biosamples.loc[biosamples.original_id==smpl]['description'].tolist()[0].replace('metagenome sample','16S-rRNA metabaecoding sequences')+' original ID %s' % biosample
    library_strategy = 'AMPLICON'
    library_source = 'GENOMIC'
    library_selection = 'PCR'
    library_layout = 'paired'
    platform = 'ILLUMINA'
    instrument_model = 'Illumina iSeq 100'
    design_description = 'Single barcode, two-step PCR, V4 fragment'
    filetype = 'fastq'
    R1 = list(glob.glob('raw_reads/%s_*_*_R1_*.fastq.gz'%smpl))[0].split('/')[-1]
    R2 = list(glob.glob('raw_reads/%s_*_*_R2_*.fastq.gz'%smpl))[0].split('/')[-1]
    sra.loc[library_ID] = [biosample,title,library_strategy,library_source,
                           library_selection,library_layout,platform,
                           instrument_model,design_description,filetype,R1,R2]

    
    
sra.to_csv('biosample_sra/sra_metadata_water.tsv',sep='\t')

In [50]:
!mkdir temp

for f in glob.glob('raw_reads/*.fastq.gz'):
    for i in biosamples.index:
        if '/%s_' % i in f:
            n = f.replace('raw_reads','temp')
            !cp $f $n

### Comments on file upload
1. put all the files in a single directory (do not zip or tar)

2. cd to this directory 

3. `ftp -p -i`

4. once inside ftp:

`ftp> open ftp-private.ncbi.nlm.nih.gov`  
`user from submission page`  
`password from submission page`  
`ftp> cd directory-from-submission-page`  
`ftp> mkdir new_dir` 
`ftp> cd new_dir`  
`ftp> mput *.fastq.gz`